import app from "ags/gtk4/app"
import { monitorFile, readFileAsync } from "ags/file"
import { exec } from "ags/process"
import { createBinding, For, This } from "ags"
import Hyprland from "gi://AstalHyprland"

import Bar from "./widgets/Bar"

// Style file paths
const scss = `./style.scss`
const css = `/tmp/ags-style-autogenerated.css`
exec(`sassc ${scss} ${css}`)

app.start({
    css: css,
    main() {
        monitorFile(
            `./style.scss`,
            (file, event) => {
                console.log('Updating CSS')
                exec(`sassc ${scss} ${css}`)
                app.reset_css()
                app.apply_css(css);
            }
        )

        const hypr = Hyprland.get_default()
        let monitors = createBinding(hypr, "monitors")
        // const monitors = createBinding(app, "monitors")

        return (
            <This this={app}>
                <For each={monitors}>
                    {(monitor) => Bar(monitor.id)}
                </For>
            </This>
        )
    }
})
