import { App } from "astal/gtk4"
import { monitorFile, readFileAsync } from "astal/file"
import { exec } from "astal/process"
import Hyprland from "gi://AstalHyprland"

import Bar from "./widgets/Bar"

// Style file paths
const scss = `./style.scss`
const css = `/tmp/ags-style-autogenerated.css`
const hypr = Hyprland.get_default()

monitorFile(
    `./style.scss`,
    (file, event) => {
        console.log('Updating CSS')
        exec(`sassc ${scss} ${css}`)
        App.reset_css()
        App.apply_css(css);
    }
)
exec(`sassc ${scss} ${css}`)

App.start({
    css: css,
    main() {
        // Create initial bars and watch for new monitors
        // Bar widget handles destruction when monitor is remoed
        hypr.get_monitors().map(monitor => Bar(monitor.id))
        hypr.connect('monitor-added', (_source, monitor) => Bar(monitor.id))
    }
})
